### ISSUE TITLE
How you ensure T_qk@T_qk^T=I?

### ISSUE THREAD

**Issue by daidaiershidi** [graldij/transformer-fusion#4]
Thank you for bringing such an interesting piece of work. In the paper, I noticed that you hoped for T_qk@T_qk^T=I. How you ensure this condition? I didn't find implementation of this in the code. Is this constraint necessary?
![image](https://github.com/user-attachments/assets/770286c4-044c-495c-8095-ab716029e5eb)

**Comment by graldij** [comment]
Hi! Thanks for the interest in our work!
Setting the option eq_t_map for the qk_fusion entry in the YAML config files, you consider together the Q and K activations/weights for the optimal transport problem. Then, the hard alignment solution returns a single permutation matrix that satisfies the given constraint.
